### ISSUE TITLE
High-resolution results

### ISSUE THREAD

**Issue by DingYikang** [xingyuuchen/tri-depth#2]
Hi, thanks for your nice work!

I'm wondering have you tested the results of Tri-depth with high-resolution (320*1024) inputs? It would be helpful if you could provide the related information or results.

Looking forward to your reply!

**Comment by xingyuuchen** [comment]
> Hi, thanks for your nice work!
> 
> I'm wondering have you tested the results of Tri-depth with high-resolution (320*1024) inputs? It would be helpful if you could provide the related information or results.
> 
> Looking forward to your reply!

Hi @DingYikang,

Thanks for your interest!
We are sorry that due to the limited time and GPU of our Lab, we did not train Tri-Depth under high-resulotion. However, you can simply set the corresponding flag in [options.py](https://github.com/xingyuuchen/tri-depth/blob/master/manydepth/options.py) to train the high-res model.
Sorry for the inconvenience.

Best, 
Xingyu

**Comment by DingYikang** [comment]
> > Hi, thanks for your nice work!
> > I'm wondering have you tested the results of Tri-depth with high-resolution (320*1024) inputs? It would be helpful if you could provide the related information or results.
> > Looking forward to your reply!
> 
> Hi @DingYikang,
> 
> Thanks for your interest! We are sorry that due to the limited time and GPU of our Lab, we did not train Tri-Depth under high-resulotion. However, you can simply set the corresponding flag in [options.py](https://github.com/xingyuuchen/tri-depth/blob/master/manydepth/options.py) to train the high-res model. Sorry for the inconvenience.
> 
> Best, Xingyu

Thanks very much for your reply!
