### ISSUE TITLE
colorful segmentation images

### ISSUE THREAD

**Issue by zixulll** [xingyuuchen/tri-depth#6]
Dear author, the segmented picture provided in FSRE-Depth is gray, may I ask how the color segmented picture you provided in the article was obtained? I want to know how to get it, thank you!

**Comment by xingyuuchen** [comment]
Hello @zixulll ,

It is grey because it has only one channel.
You can easily convert it into 3 channel (RGB) thr the `color_map`.
AFAIK, the `matplotlib.pyplot` library provides such an API.
E.g., see our code [here](https://github.com/xingyuuchen/tri-depth/blob/master/manydepth/trainer.py#L937).

Best,
Xingyu

**Comment by zixulll** [comment]
Thank you for your reply. The problem has been resolved!
